MONGODB_HOST: mongodb-{{ env }}.wasdaws.shop
REDIS_HOST: redis-{{ env }}.wasdaws.shop
CATALOGUE_HOST: catalogue-{{ env }}.wasdaws.shop
CART_HOST: cart-{{ env }}.wasdaws.shop
USER_HOST: user-{{ env }}.wasdaws.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.wasdaws.shop
MYSQL_HOST: mysql-{{ env }}.wasdaws.shop
SHIPPING_HOST: shipping-{{ env }}.wasdaws.shop
PAYMENT_HOST: payment-{{ env }}.wasdaws.shop