# $ANSIBLE_VAULT;1.1;AES256
# 37313439363135616261333339333536633462333564336130663234333561633831633139376439
# 3262313430653662373664363937383731326135306361660a323464643134643661356536363665
# 63343030373733613164616135356438333838323437386334656432323961366266383464663663
# 3834326462663362370a313534326235313566636363306662363362613436326534633964643566
# 39323766646463306436386233643265343265386531353965306633336133653530663361626566
# 3231346661323738646333396266353335636662376135623166

# ansible-playbook -i inventory.ini main.yaml -e "component=mysql" --ask-vault-pass
# we create vault using ansible-vault create mysql.yaml in ansible server [we need to setup vault password there]
# for opening the vault( which stores MYSQL_ROOT_PASSWORD) instead of manual entry via commands we create sudo vim mysql_vault_pass.txt and 
# pass it by providing by key "vault_password_file" in ansible.cfg [Which eliminates --ask-vault-pass since we have provided in ansible.cfg]